version: '2'
services:
  mongo:
    restart: always
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      BLAHDATA : /data/blah
    volumes_from:
      - blah_data
  blah:
    restart: always
    build: .
    environment:
      - MONGODB_URI=mongo:27017
      - GOOGLE_APPLICATION_CREDENTIALS=credentials.json
    ports:
      - "5000:5000"
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - .:/app

  blah_data:
    image: alpine:latest
    container_name: blah_data
    volumes:
      - /data/blah
    command: "true"

