version: '2'
services:
  mongo:
    restart: always
    image: mongo:latest
    ports:
      - "27017:27017"   
  blah:
    restart: always
    build: .
    environment:
      - MONGO_URL=mongo:27017
      - GOOGLE_APPLICATION_CREDENTIALS=credentials.json
    ports:
      - "5000:5000"
    links:
      - mongo
    depends_on:
      - mongo

